# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/aiblog',
                'doc_host': 'https://38leinaD.github.io',
                'git_url': 'https://github.com/38leinaD/aiblog',
                'lib_path': 'aiblog'},
  'syms': {'aiblog.core': {'aiblog.core.foo': ('core.html#foo', 'aiblog/core.py')}}}
